language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6'
before_script:
  - npm prune
script:
  - npm run test
  - npm run build
after_success:
  - if [ "$TRAVIS_BRANCH" = "develop" ]; then echo "Build passed, not publishing from branch: [$TRAVIS_BRANCH]"; fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then echo "Build passed, semantic-releasing to https://www.npmjs.com from: [$TRAVIS_BRANCH] ..." && npm run semantic-release; fi
branches:
  except:
    - /^v\d+\.\d+\.\d+$/